baseURL = "https://tubular-profiterole-c403d5.netlify.app/"
languageCode = "en-us"
title = "iamian@dev"
theme = "hugo-theme-console"
copyright = "Copyright {year} Ian Montgomery"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 


  [[params.navlinks]]
  name = "cv/"
  url = "cv/"

  [[params.navlinks]]
  name = "blog/"
  url = "blog/"

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"


[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 75
  resampleFilter = 'Box'

  




